# Generated by Django 5.2.8 on 2025-11-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Системное имя меню, используется в теге {% draw_menu 'name' %}", max_length=100, unique=True)),
                ('verbose_name', models.CharField(blank=True, help_text='Человеко-читаемое название (для админки)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, help_text='Явный URL', max_length=255)),
                ('named_url', models.CharField(blank=True, help_text='Имя URL из urls.py', max_length=100)),
                ('sort_order', models.IntegerField(default=0, help_text='Порядок сортировки внутри одного уровня')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menuitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
